// Barrel export for all scene modules
export { signaleren } from './signaleren'
export { doktrConsult } from './doktr-consult'
export { begrijpen } from './begrijpen'
export { begeleiden } from './begeleiden'
export { verbinden } from './verbinden'
export { beslissen } from './beslissen'
export { ondersteunen } from './ondersteunen'
export { herstellen } from './herstellen'
export type { SceneModule } from './types'
